var sortes;

export default sortes = [
    'Uma pessoa bonita, inteligente e amorosa entrará em sua vida.',
    'Um amigo duvidoso pode ser um inimigo camuflado.',
    'Um amigo fiel é uma defesa forte.',
    'Uma pena na mão é melhor do que um pássaro no ar.',
    'Um novo começo irá colocá-lo no seu caminho.',
    'Um amigo pede apenas seu tempo, não seu dinheiro.',
    'Um amigo é um presente que você dá a si mesmo.',
    'Um jogador não só perderá o que possui, mas também perderá o que não possui.',
    'Um ovo de ouro de oportunidade cai em seu colo este mês.',
    'Uma boa amizade costuma ser mais importante do que um romance apaixonado.',
    'Um bom momento para terminar tarefas antigas.',
    'Um palpite é a criatividade tentando lhe dizer algo.',
    'Um amigo para toda a vida logo será feito.',
    'Uma vida inteira de felicidade está à sua frente.',
    'Um coração leve carrega você em todos os momentos difíceis.',
    'Uma nova perspectiva virá com o novo ano.',
    'Uma pessoa nunca é muito velha para aprender.',
    'Uma pessoa de palavras e não de ações é como um jardim cheio de ervas daninhas.',
    'Uma agradável surpresa está esperando por você.',
    'Um lápis curto geralmente é melhor do que uma longa memória em qualquer dia.',
    'Uma pequena doação é necessária. É a coisa certa a fazer.',
    'Um sorriso é o seu tapete de boas-vindas pessoal.',
    'Uma longa jornada tranquila! Grandes Expectativas.',
    'Uma voz suave pode ser terrivelmente persuasiva.',
    'Uma vida verdadeiramente rica contém amor e arte em abundância.',
    'Aceite algo que você não pode mudar e se sentirá melhor.',
    'A aventura pode ser uma verdadeira felicidade.',
    'O conselho é como beijar. Não custa nada e é uma coisa agradável de se fazer.',
    'Conselhos, quando mais necessários, são menos atendidos.',
    'Todo o esforço que você está fazendo, no final das contas, será recompensado.',
    'Todos os problemas que você tem passarão muito rapidamente.',
    'Tudo irá bem com seu novo projeto.',
    'Todo o seu trabalho árduo logo terá retorno.',
    'Permita que a compaixão guie suas decisões.',
    'Um conhecido do passado afetará você em um futuro próximo.',
    'Um romance agradável pode começar a aparecer.',
    'Uma pessoa importante oferecerá suporte a você.',
    'Uma polegada de tempo é uma polegada de ouro.',
    'Qualquer decisão que você tenha que tomar amanhã é uma boa decisão.',
    'Ao toque do amor, todos se tornam poetas.',
    'Tenha cuidado ou você pode cair em alguns truques hoje.',
    'A beleza em suas várias formas atrai você.',
    'Como você exige mais de si mesmo, os outros o respeitam profundamente.',
    'Acredite em si mesmo e nos outros também.',
    'Acredite que isso pode ser feito.',
    'Melhor perguntar duas vezes do que se perder uma vez.',
    'Aguarde sua hora, pois o sucesso está próximo.',
    'Grave seu nome em seu coração e não em mármore.',
    'A mudança está acontecendo em sua vida, então siga o fluxo!',
    'Competências como a sua são subestimadas.',
    'Parabéns! Você está no seu caminho.',
    'Posso obter algumas instruções para o seu coração?',
    'A cortesia começa em casa.',
    'A cortesia é contagiante.',
    'A curiosidade mata o tédio. Nada pode matar a curiosidade.',
    'Dedique-se com a mente tranquila à tarefa que tem em mãos.',
    'Não se afaste do caminho que o destino designou.',
    'Determinação é o que você precisa agora.',
    'Diligência e modéstia podem elevar seu status social.',
    'A descrença destrói a magia.',
    'Afaste-se do vão.',
    'Não se deixe intimidar pela eloqüência dos outros.',
    'Não exija pela alma de alguém se você já tem o coração dele.',
    'Não deixe as ambições obscurecerem o pequeno sucesso.',
    'Não faça trabalho extra para você.',
    'Não se subestime. Os seres humanos têm potenciais ilimitados.',
    'Você sabia que a pessoa mais ocupada tem a maior quantidade de tempo?',
    'Não desanime, porque toda tentativa errada descartada é mais um passo à frente.',
    'Não confunda imprudência com confiança.',
    'Não perca tempo. Invista.',
    'Não apenas pense, aja!',
    'Não deixe que os amigos se intrometam em você, trabalhe com calma e em silêncio.',
    'Não deixe o passado e os detalhes inúteis sufocarem sua existência.',
    'Não deixe suas limitações obscurecerem seus talentos.',
    'Não se preocupe; a prosperidade vai bater à sua porta em breve.',
    'A cada dia, obrigue-se a fazer algo que prefere não fazer.',
    'A educação é a capacidade de enfrentar as situações da vida.',
    'Abrace esse relacionamento de amor que você tem!',
    'Emule o que você admira em seus pais.',
    'Emule o que você respeita em seus amigos.',
    'Cada flor desabrocha em seu próprio tempo doce.',
    'Todo homem sábio começou fazendo muitas perguntas.',
    'Cada dia em sua vida é uma ocasião especial.',
    'Onde quer que você escolha ir, rostos amigáveis ​​irão cumprimentá-lo.',
    'Espere muito de si mesmo e pouco dos outros.',
    'O fracasso é a chance de fazer melhor da próxima vez.',
    'O fracasso é o caminho da persistência do arrendamento.',
    'Medo e desejo - dois lados da mesma moeda.',
    'A coragem destemida é a base da vitória.',
    'Alimentar uma vaca com rosas não leva a uma apreciação extra.',
    'Primeiro pense no que você deseja fazer; então faça o que você tem que fazer.',
    'Siga o caminho do meio. Nenhum dos extremos o fará feliz.',
    'Pois o ódio nunca é vencido pelo ódio. O ódio é conquistado pelo amor.',
    'Para as coisas que temos que aprender antes de podermos fazer, aprendemos fazendo-as.',
    'Fortune Not Found: Abort, Retry, Ignore?',
    'Ouvir vem sabedoria e falar arrependimento.',
    'De agora em diante, sua bondade o levará ao sucesso.',
    'Defina sua mente - a confiança o conduzirá.',
    'Defina sua mente ... a confiança o conduzirá.',
    'Vá para o ouro hoje! Você será o campeão de tudo.',
    'Vá descansar; você merece isso.',
    'Boas notícias serão enviadas a você por correio.',
    'Boas notícias chegarão a você pelo correio.',
    'É bom começar bem, é melhor terminar bem.',
    'A felicidade começa enfrentando a vida com um sorriso e uma piscadela.',
    'A felicidade lhe trará boa sorte.',
    'A vida feliz está bem na sua frente.',
    'Palavras duras não quebram ossos, palavras bonitas não quebram pastinacas.',
    'Tenha um lindo dia.',
    'Aquele que não espera gratidão nunca ficará desapontado.',
    'Aquele que sabe que tem o suficiente é rico.',
    'Quem conhece os outros é sábio. Aquele que conhece a si mesmo é iluminado.',
    'Ajuda! Estou preso em uma padaria chinesa!',
    'Quantos de vocês acreditam em psicocinese? Levante minha mão.',
    'Sua aparência depende de onde você vai.',
    'Eu aprendo indo para onde tenho que ir.',
    'Se um verdadeiro senso de valor deve ser seu, ele deve vir por meio do serviço.',
    'Se a certeza fosse verdade, nunca estaríamos errados.',
    'Se você dá continuamente, você continuamente terá.',
    'Se você procurar nos lugares certos, poderá encontrar algumas boas ofertas.',
    'Se você pensa que pode fazer algo ou pensa que não pode fazer algo, você está certo.',
    'Se você deseja ver o melhor nos outros, mostre o melhor de si mesmo.',
    'Se seus desejos não forem extravagantes, eles serão atendidos.',
    'Se seus desejos não forem extravagantes, eles serão concedidos.',
    'Se você estiver se sentindo deprimido, tente se lançar ao trabalho.',
    'A imaginação governa o mundo.',
    'Para receber, é preciso primeiro dar.',
    'No final, todas as coisas serão conhecidas.',
    'Neste mundo de contradições, é melhor ser alegre do que sábio.',
    'Poderia ser melhor, mas é bom o suficiente.',
    'É melhor ser um otimista e provar que é um tolo do que ser um pessimista e provar que está certo.',
    'É melhor lidar com os problemas antes que eles surjam.',
    'É uma honra defender o que é certo, por mais impopular que pareça.',
    'Vale a pena revisar algumas lições antigas.',
    'É preciso coragem para admitir a falha.',
    'Não é a quantidade de tempo que você dedica, mas o que você dedica ao tempo que conta.',
    'É hora de começar. Seu espírito se elevará de acordo.',
    'Mantenha o rosto voltado para o sol e nunca verá sombras.',
    'Deixe o mundo se encher de tranquilidade e boa vontade.',
    'Como o fluxo do rio para o mar. Algo está destinado a ser.',
    'Não dê ouvidos a palavras vãs de língua vazia.',
    'Ouça a todos. As ideias vêm de todos os lugares.',
    'Viver com o compromisso com a excelência levará você longe.',
    'Vida longa está reservada para você.',
    'O amor é um fogo quente para manter a alma aquecida.',
    'O amor é como um doce remédio, bom até a última gota.',
    'O amor ilumina o mundo.',
    'Ama a verdade, mas perdoa o erro.',
    'O homem nasce para viver e não está preparado para viver.',
    'A mente que se abre a uma nova ideia jamais voltará ao seu tamanho original',
    'Muitos viajarão para ouvir você falar.',
    'Aconselha-se a meditação com um velho inimigo.',
    'As milhas são percorridas uma etapa de cada vez.',
    'Natureza, tempo e paciência são os três grandes médicos.',
    'Nunca tema! O fim de algo marca o início de algo novo.',
    'Novas ideias podem ser lucrativas.',
    'Novas pessoas trarão novas realizações, especialmente sobre grandes questões.',
    'Ninguém pode voltar para o futuro.',
    'Nada é mais difícil e, portanto, mais precioso do que ser capaz de decidir.',
    'Agora é um bom momento para comprar ações.',
    'Agora é a hora de seguir em frente e perseguir esse interesse amoroso!',
    'Agora é a hora de tentar algo novo',
    'Agora é a hora de tentar algo novo.',
    'Observe todos os homens, mas acima de tudo você mesmo.',
    'Ninguém pode ocupar o lugar do outro, ao contrário, ele deve superar os sapatos antigos.',
    'Uma das primeiras coisas que você deve procurar em um problema é seu lado positivo.',
    'Outros podem ajudá-lo agora.',
    'Moedas do céu vão chegar à sua porta este ano!',
    'As pessoas são atraídas por suas características Delicadas.',
    'As pessoas acham difícil resistir à sua maneira persuasiva.',
    'Talvez você esteja se concentrando muito em economizar.',
    'A atividade física vai melhorar drasticamente sua perspectiva hoje.',
    'Escolha batalhas grandes o suficiente para importar, pequenas o suficiente para vencer.',
    'Dê ênfase especial à velha amizade.',
    'Po diz: Pandas gostam de comer bambu, mas eu prefiro o meu mergulhado em chocolate.',
    'A prática leva à perfeição.',
    'As medidas de proteção evitarão desastres dispendiosos.',
    'Coloque sua mente no planejamento hoje. Olhe para o futuro.',
    'Lembre-se do aniversário, mas nunca da idade.',
    'Lembre-se de compartilhar a boa e a má sorte com seus amigos.',
    'O descanso tem um efeito pacífico em sua saúde física e emocional.',
    'Descansar bem é tão importante quanto trabalhar duro.',
    'Romance leva você em uma nova direção.',
    'Saboreie sua liberdade - ela é preciosa.',
    'Diga olá para os outros. Você terá um dia mais feliz.',
    'O autoconhecimento é um processo que dura a vida toda.',
    'Compartilhe suas alegrias e tristezas com sua família.',
    'Examine seu passado para ter uma ideia melhor do presente.',
    'A preguiça torna todas as coisas difíceis; indústria tudo fácil.',
    'Pequenas confidências marcam o início de uma amizade.',
    'A sociedade prepara o crime; o criminoso o comete.',
    'Alguém de quem você gosta busca reconciliação.',
    'Logo a vida se tornará mais interessante.',
    'Fique ereto. Não se despreze.',
    'Ficar perto de casa será o melhor para o seu moral hoje',
    'Pare de procurar para sempre, a felicidade está ao seu lado.',
    'Razões fortes fazem ações fortes.',
    'Sucesso é uma jornada, não um destino.',
    'O sucesso é o fracasso virado do avesso.',
    'O sucesso vai de fracasso em fracasso, sem perda de entusiasmo.',
    'Nadar é fácil. Ficar flutuando é difícil.',
    'Tome cuidado e a sensibilidade que você mostrar para com os outros voltará para você.',
    'Pegue a estrada principal.',
    'Tecnologia é a arte de organizar o mundo para que não percebamos.',
    'A austeridade que você vê ao seu redor cobre a riqueza da vida como um véu.',
    'A melhor previsão do futuro é o passado.',
    'A mudança que você iniciou já tem efeitos de longo alcance. Esteja pronto.',
    'A mudança que você iniciou já tem efeitos de longo alcance. Esteja pronto.',
    'O primeiro homem pega a ostra, o segundo homem fica com a casca.',
    'A maior conquista da vida é levantar-se novamente após uma queda.',
    'Quanto mais você trabalhar, mais sorte terá.',
    'A vida noturna é para você.',
    'Aquele que reconhece a ilusão não age como se ela fosse real.',
    'As únicas pessoas que nunca falham são aquelas que nunca tentam.',
    'A pessoa que não defende algo, cairá em nada.',
    'A filosofia de um século é o senso comum do próximo.',
    'Os santos são os pecadores que continuam tentando.',
    'O segredo para bons amigos não é segredo para você.',
    'As pequenas cortesias adoçam a vida, quanto mais a enobrecem.',
    'A coisa inteligente a fazer é começar a confiar em suas intuições.',
    'A pessoa forte sabe como resistir a perdas substanciais.',
    'A maneira certa de prever o futuro é inventá-lo.',
    'A parte verdadeiramente generosa, mesmo com os indignos.',
    'O valor não está em alguma coisa em particular, mas no desejo colocado nessa coisa.',
    'O tempo está maravilhoso.',
    'É hora de cautela, mas não de medo.',
    'Não há erro tão grande quanto o de estar sempre certo.',
    'Não há sabedoria maior do que a bondade.',
    'Não há maior prazer do que ver seus entes queridos prosperar.',
    'Não existe um gato comum.',
    'As coisas não acontecem simplesmente; eles acontecem apenas.',
    'Aqueles que se importam farão o esforço.',
    'Tempo e paciência são necessários, pois muitas surpresas o aguardam !. ',
    'O tempo é precioso, mas a verdade é mais preciosa do que o tempo',
    'Para se conhecer, é preciso se afirmar.',
    'Para o mundo você pode ser uma pessoa, mas para uma pessoa você pode ser o mundo.',
    'Hoje é o conservar-se, pois as coisas simplesmente não se movem.',
    'Hoje, sua boca pode estar se movendo, mas ninguém está ouvindo.',
    'Esta noite você ficará cego pela paixão.',
    'Use sua eloqüência onde for mais útil.',
    'Primeiro fazemos nossos hábitos e, depois, nossos hábitos nos fazem.',
    'Bem-vindo a mudança.',
    '“Bem-vindo” é uma palavra poderosa.',
    'Bem feito é melhor do que bem dito.',
    'O que está escondido em uma caixa vazia?',
    'O que é seu no meu, e o que é meu é meu.',
    'Quando mais se tornar muito. É o mesmo que não ser suficiente.',
    'Quando seu coração é puro, sua mente está clara.',
    'Te desejo felicidade.',
    'Com a idade, vem a sabedoria.',
    'Sua aventura pode levar à felicidade.',
    'Você sempre traz felicidade aos outros.',
    'Você é uma pessoa de outra época.',
    'Você é um contador de histórias talentoso.',
    'Você é admirado por todos por seu talento e habilidade.',
    'Você está quase lá.',
    'Você está ocupado, mas feliz.',
    'Você é generoso ao extremo e sempre pensa no outro.',
    'Você vai ter algumas roupas novas.',
    'Você está em boas mãos esta noite.',
    'Você está interessado em educação superior, seja material ou espiritual.',
    'Você é modesto e cortês.',
    'Você nunca é egoísta com seus conselhos ou ajuda.',
    'Você é o próximo na fila para promoção em sua empresa.',
    'Você tem o sonho de uma vida. Diga sim!',
    'Você tem a mente aberta e é rápido para fazer novos amigos.',
    'Você é sólido e confiável.',
    'Em breve, você mudará sua atual linha de trabalho.',
    'Você é talentoso de várias maneiras.',
    'Você é o mestre de todas as situações.',
    'Você é muito expressivo e positivo em palavras, atos e sentimentos.',
    'Você está trabalhando duro.',
    'Você começa a perceber como é importante compartilhar suas crenças pessoais.',
    'Você pode manter um segredo.',
    'Você pode ver muito apenas olhando.',
    'Você não pode roubar a segunda base e manter o pé no primeiro.',
    'Você deseja reconhecimento e o encontrará.',
    'Você tem um profundo apreço pelas artes e pela música.',
    'Você tem um profundo interesse por tudo o que é artístico.',
    'Você tem um coração amigável e é muito admirado.',
    'Você tem um talento astuto para detectar a falta de sinceridade.',
    'Você deseja a perfeição.',
    'Você tem uma mente ativa e uma imaginação aguçada.',
    'Você tem uma natureza ambiciosa e pode fazer seu próprio nome.',
    'Você tem um equipamento incomum para o sucesso, use-o de maneira adequada.',
    'Você excedeu o que era esperado.',
    'Você teve um bom começo. Trabalhe mais!',
    'Você tem o poder de escrever sua própria fortuna.',
    'Você deseja a perfeição.',
    'Você sabe para onde está indo e como chegar lá.',
    'Você está bonita.',
    'Você adora desafios.',
    'Você adora comida chinesa.',
    'Você faz as pessoas perceberem que existem outras belezas no mundo.',
    'Você nunca hesita em enfrentar os problemas mais difíceis.',
    'Você nunca sabe quem você toca.',
    'Você só valoriza o que perdeu.',
    'Você procura proteger aqueles que ama e gosta do papel de provedor.',
    'Você deve ser capaz de ganhar dinheiro e mantê-lo.',
    'Você deve ser capaz de realizar e concluir qualquer coisa.',
    'Você deve pagar por este cheque. Seja generoso.',
    'Você sabe como se divertir com os outros e desfrutar da sua solidão.',
    'Você sempre estará rodeado de verdadeiros amigos.',
    'Você sempre obterá o que deseja por meio de seu charme e personalidade.',
    'Você sempre terá boa sorte em seus assuntos pessoais.',
    'Você será um grande sucesso tanto no mundo dos negócios quanto na sociedade.',
    'Você será abençoado com longevidade.',
    'Você ficará agradavelmente surpreso esta noite.',
    'Você estará compartilhando ótimas notícias com todas as pessoas que você ama.',
    'Você terá sucesso em seu trabalho.',
    'Você estará viajando e entrando em uma fortuna.',
    'Você terá um sucesso incomum nos negócios.',
    'Você se tornará um grande filantropo em seus últimos anos.',
    'Você se tornará cada vez mais rico.',
    'Você desfrutará de boa saúde.',
    'Você desfrutará de boa saúde; você estará rodeado de luxo.',
    'Você encontrará grande contentamento nas atividades diárias e rotineiras.',
    'Você terá uma excelente capacidade para desfrutar a vida.',
    'Você terá moedas de ouro por alqueire.',
    'Você herdará uma grande soma de dinheiro.',
    'Você fará mudanças para melhor.',
    'Você logo estará rodeado de bons amigos e risos.',
    'Você terá uma chance em um futuro próximo.',
    'Você viajará por todo o mundo, tanto a lazer quanto a negócios.',
    'Você viajará por todo o mundo, tanto a lazer quanto a negócios.',
    'Suas habilidades são incomparáveis.',
    'Sua habilidade é apreciada.',
    'Sua habilidade de fazer malabarismos com muitas tarefas o levará longe.',
    'Sua maior virtude é sua modéstia.',
    'Seu personagem pode ser descrito como natural e irrestrito.',
    'Suas dificuldades o fortalecerão.',
    'Seus sonhos nunca são bobos; dependem deles para guiá-lo.',
    'Seus sonhos valem seus melhores esforços para alcançá-los.',
    'Sua energia retorna e você faz as coisas.',
    'Sua família é jovem, talentosa e atraente.',
    'Seu primeiro amor nunca se esqueceu de você.',
    'Seu objetivo será alcançado muito em breve.',
    'Sua felicidade está diante de você, não atrás de você! Cuide disso.',
    'Seu trabalho duro vai render hoje.',
    'Seu coração sempre se dará a conhecer por meio de suas palavras.',
    'Sua casa é o centro de um grande amor.',
    'Seus ideais estão bem ao seu alcance.',
    'Sua infinita capacidade de paciência será recompensada mais cedo ou mais tarde.',
    'Suas qualidades de liderança serão testadas e comprovadas.',
    'Sua vida será feliz e pacífica.',
    'Sua vida ficará cada vez mais emocionante.',
    'Sua vida amorosa será feliz e harmoniosa.',
    'Seu amor pela música será uma parte importante de sua vida.',
    'Sua lealdade é uma virtude, mas não quando combinada com uma teimosia cega.',
    'Sua mentalidade é alerta, prática e analítica.',
    'Sua mente é criativa, original e alerta.',
    'Sua mente é o seu maior patrimônio.',
    'Seu humor sinaliza um período de mudança.',
    'Seu raciocínio rápido o livrará de uma situação difícil.',
    'Sua reputação é sua riqueza.',
    'Seu sucesso surpreenderá a todos.',
    'Seus talentos serão reconhecidos e devidamente recompensados.',
    'Seus interesses de trabalho podem capturar o mais alto status ou prestígio.'
];
